# Generated by Django 6.0.4 on 2026-04-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='User name')),
                ('music_name', models.CharField(max_length=20, verbose_name='Music name')),
                ('music', models.FileField(upload_to='', verbose_name='Music')),
            ],
        ),
    ]
